### ISSUE TITLE
How can I visit sails controller/action via get method?

### ISSUE THREAD

**Issue by tonyts** [Tarrask/sails-generate-new-webpack-vue#1]
I have a `UserController `and a `User` model, managing users with sails Blueprint API, and I try to use `io.socket.get('/user', cb)` to monitor the users' status. But I find that in dev mode, all get method route to index.html. How can I visit sails controller/action via get method?

**Comment by Tarrask** [comment]
Hi,

Please have a look here: https://github.com/Tarrask/sails-hook-webpack-vue/issues/1#issuecomment-315680313

It should work if you upgrade sails-hook-webpack-vue from 0.1.3 to 0.1.4.
