### ISSUE TITLE
use cnpm will run error

### ISSUE THREAD

**Issue by elliottssu** [Tarrask/sails-generate-new-webpack-vue#3]
npm is work fine, but if you use cnpm,  need to degrade webpack 2.7.0 ,to fix Hot Module ReplaceMent(HMR) conflict version
both of them works method is different

**Comment by Tarrask** [comment]
Hi,
Can you clarify this a bit. I can't see any reference to webpack 2.7, for what I can see, it jump from 2.6 to 3.0.

And do you mean webpack-hot-middleware has breaking change some where ? Between which version ?
