### ISSUE TITLE
Unable to locate testing webpack config

### ISSUE THREAD

**Issue by robertmain** [Tarrask/sails-generate-new-webpack-vue#4]
When I initially lifted my new sails app - I got an error in the console saying that it couldn't find `webpack.test.conf.js`. I'm fairly handy with webpack so I just edited `config/webpack.js` and changed it to point to `webpack.dev.config.js` instead and this fixed the issue. However, you might want to look into this..

**Comment by Tarrask** [comment]
This append when you create a app without the testing. The webpack does not create the required file.

The problem, is that when generating the `config/webpack.js` file, I don't know what your answers was when generating the webpack app.

I'll have to find a way to conditionally require the find at runtime...

**Comment by robertmain** [comment]
>This append when you create a app without the testing.

What do you mean? I did what it said in the README instructions...

**Comment by Tarrask** [comment]
When you answer the vue-cli questions, if you choose `no` when it ask `Setup unit tests with Karma + Mocha?`, the script does not create the `webpack.test.conf.js` I guess it why you get this error.

**Comment by robertmain** [comment]
Ohhhhh! I see. OK - that makes sense :)
